const QRCode = require('qrcode');

exports.generateVCF = async (req, res) => {
  const { vcardData } = req.body;

  if (!vcardData || !vcardData.firstName || !vcardData.lastName) {
    return res.status(400).json({ error: 'First name and last name are required' });
  }

  try {
    const vcardContent = `BEGIN:VCARD
VERSION:3.0
FN:${vcardData.firstName} ${vcardData.lastName}
N:${vcardData.lastName};${vcardData.firstName};;;
EMAIL:${vcardData.email || ''}
TEL:${vcardData.phone || ''}
ADR:;;${vcardData.street || ''};${vcardData.city || ''};${vcardData.state || ''};;${vcardData.country || ''}
URL:${vcardData.website || ''}
NOTE:Generated by VCard Builder
END:VCARD`;

    const qrCodeDataURL = await QRCode.toDataURL(vcardContent);

    res.json({ vcard: vcardContent, qrCode: qrCodeDataURL });
  } catch (error) {
    console.error('Error generating VCF:', error);
    res.status(500).json({ error: 'Failed to generate VCF' });
  }
};
